# Generated by Django 4.2.7 on 2023-12-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_bookpurchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
